#!/bin/sh
### BEGIN INIT INFO
# Provides:          sm-t280-display
# Required-Start:    $local_fs $remote_fs udev
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Panel refresh (FBIOPAN loop) and an XFCE session on fb0
### END INIT INFO
# The sprdfb command-mode panel only updates on FBIOPAN_DISPLAY, so a small
# helper keeps re-panning page 0 while Xorg (fbdev) draws into the framebuffer.
log() { echo "sm-t280-display: $*" > /dev/kmsg; }
case "$1" in
start)
    start-stop-daemon --start --background --make-pidfile --pidfile /run/fbpan.pid \
        --exec /usr/local/sbin/fbpan -- loop 33
    start-stop-daemon --start --background --make-pidfile --pidfile /run/xsession.pid \
        --chuid debian --chdir /home/debian --exec /usr/bin/xinit -- \
        /usr/bin/startxfce4 -- /usr/bin/Xorg :0 vt1 -nolisten tcp
    log "started"
    ;;
stop)
    start-stop-daemon --stop --quiet --pidfile /run/xsession.pid
    start-stop-daemon --stop --quiet --pidfile /run/fbpan.pid
    ;;
esac
